[versions]
kotlin                    = "2.3.21"
spring-boot               = "4.0.6"
spring-dependency-mgmt    = "1.1.7"
spring-modulith           = "2.0.6"
timefold                  = "2.0.0"
temporal                  = "1.34.0"
sentry                    = "8.27.0"
springdoc-openapi         = "3.0.2"
graalvm-buildtools        = "0.10.4"
kover                     = "0.9.1"
testcontainers            = "2.0.0"
mockk                     = "1.14.0"

[libraries]
springdoc-openapi-webmvc  = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui",  version.ref = "springdoc-openapi" }
temporal-spring-boot      = { module = "io.temporal:temporal-spring-boot-starter",            version.ref = "temporal" }
mockk                     = { module = "io.mockk:mockk",                                      version.ref = "mockk" }

[plugins]
kotlin-jvm                = { id = "org.jetbrains.kotlin.jvm",               version.ref = "kotlin" }
kotlin-spring             = { id = "org.jetbrains.kotlin.plugin.spring",     version.ref = "kotlin" }
kotlin-jpa                = { id = "org.jetbrains.kotlin.plugin.jpa",        version.ref = "kotlin" }
spring-boot               = { id = "org.springframework.boot",               version.ref = "spring-boot" }
spring-dep-mgmt           = { id = "io.spring.dependency-management",        version.ref = "spring-dependency-mgmt" }
graalvm-native            = { id = "org.graalvm.buildtools.native",          version.ref = "graalvm-buildtools" }
kover                     = { id = "org.jetbrains.kotlinx.kover",            version.ref = "kover" }
